### Валидная авторизация
POST http://localhost:8082/login
Content-Type: application/json

{
  "login": "ffff",
  "password": "qwerty"
}




### Регистрация пользователя
POST http://localhost:8082/register
Content-Type: application/json

{
  "login": "ffff",
  "password": "qwerty"
}


### Ручка
DELETE http://localhost:8082/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2MH0.7VyNneiU6e7qDNC65bKzBPaUhnqUXejinWEHmSRzMzo
Content-Type: application/json

{
  "password": "qwerty"
}