### Валидная авторизация
POST http://localhost:8082/login
Content-Type: application/json

{
  "login": "test",
  "password": "test"
}




### Регистрация пользователя
POST http://localhost:8082/register
Content-Type: application/json

{
  "login": "test",
  "password": "test"
}


### Ручка
DELETE http://localhost:8082/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3Mn0.Gaz9MXN9u6iKczftNCxq9p736t_AY4nxl86gXfljlvM
Content-Type: application/json

{
  "password": "test"
}