### Валидная авторизация
POST http://localhost:8082/login
Content-Type: application/json

{
  "login": "dovgalb",
  "password": "qwerty"
}


### Невалидная авторизация
POST http://localhost:8082/login
Content-Type: application/json

{
  "login": "dovgalb",
  "password": "qwertyе"
}