### GET request to example server
POST http://localhost:8082/register
Content-Type: application/json

{
  "login": "dovgalb",
  "password": "qwerty"
}

###

### GET request to example server
POST http://localhost:8082/register
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###